name: iot_client
description: A Flutter application for IoT client.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # path: ^1.8.0
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  lints: ^5.0.0
  test: ^1.24.0

flutter:
  uses-material-design: true
  assets:
    - lib/icons/